name: Deployment hotel-Miranda-Dashboard

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '18.15.0'

      - name: create envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          USER_ADMIN: ${{ secrets.USER_ADMIN }}
          PASSWORD_ADMIN: ${{ secrets.PASSWORD_ADMIN }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_COLLECTION: ${{ secrets.DB_COLLECTION }}
          DB_CLUSTER: ${{ secrets.DB_CLUSTER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - name: install dependencies
        run: npm install

      - name: build project
        run: npm run build
        
      - name: deploy in lambda
        uses: serverless/github-action@v3.2
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          